# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [31]:
# Import torch
import torch


# Create random tensor
x = torch.rand(7,7)
x, x.shape


(tensor([[0.2086, 0.6709, 0.2020, 0.4891, 0.5210, 0.8223, 0.1220],
         [0.1567, 0.2097, 0.8500, 0.3203, 0.9217, 0.6808, 0.5633],
         [0.4963, 0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089],
         [0.2379, 0.9037, 0.0942, 0.4641, 0.9946, 0.6806, 0.5142],
         [0.0667, 0.7477, 0.1439, 0.3581, 0.3322, 0.4260, 0.5055],
         [0.9124, 0.5624, 0.9478, 0.8059, 0.1839, 0.7243, 0.1466],
         [0.2881, 0.6471, 0.6651, 0.8751, 0.3390, 0.5008, 0.7574]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [33]:
# Create another random tensor
y = torch.rand(1,7)
y

# Perform matrix multiplication 
z = torch.matmul(x, y.T)

z, z.shape




(tensor([[1.2539],
         [1.1355],
         [1.2708],
         [1.3344],
         [0.9095],
         [2.0434],
         [1.4647]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [37]:
# Set manual seed
torch.manual_seed(0)

x = torch.rand(7,7)
y = torch.rand(1,7)

u = torch.matmul(x, y.T)

u, u.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [63]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")


# Create two random tensors on GPU

x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)

x, y


Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [64]:
# Perform matmul on tensor_A and tensor_B

x.shape, y.shape

u = torch.matmul(x, y.T)

u, u.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [65]:
# Find max
i = torch.max(u)
# Find min
l = torch.min(u)

i, l


(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [66]:
# Find arg max
arg_max = torch.argmax(u)

# Find arg min
arg_min = torch.argmin(u)


arg_max, arg_min

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [87]:
# Set seed
torch.manual_seed(7)

# Create random tensor
k = torch.rand(1, 1, 1, 10)

# Remove single dimensions
k_single = k.squeeze()

# Print out tensors and their shapes

print(k, f"\nshape of k tensor: {k.shape}")
print("\n")
print(k_single, f"\nshape of k_single tensor: {k_single.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
shape of k tensor: torch.Size([1, 1, 1, 10])


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
shape of k_single tensor: torch.Size([10])
